Add configuration parameter for automatically sending an initial response
onsip/SIP.js pull request #892
Opened 2021-01-07 15:52 UTC by jamesaylett

Resolves issue https://github.com/onsip/SIP.js/issues/865.

Adds a configuration parameter to allow turning off automatically sending provisional responses. Defaults to current behaviour.

2021-01-20 18:42 UTC, john-e-riordan commented on src/api/user-agent-options.ts
> +  sendInitialProvisionalResponse?: boolean;
Please match style by adding this new option in alphabetical order - thanks.

2021-01-20 18:43 UTC, john-e-riordan requested changes

2021-01-20 18:43 UTC, john-e-riordan commented on src/api/user-agent.ts
> +      sendInitialProvisionalResponse: true
Please match style by adding this new option in alphabetical order - thanks.

2021-01-20 18:44 UTC, john-e-riordan commented
Other than the suggested changes to matching style, looks good to me.

2021-01-20 18:44 UTC, john-e-riordan commented
Oh - docs will need to be re-generated.

2021-01-26 15:13 UTC, merged

2021-01-26 15:13 UTC, james-criscuolo commented
Thanks again! I'll make the suggested changes in a follow-up commit now.